/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jarrett
 */
public class DnDToolbox extends javax.swing.JFrame {

    /**
     * Creates new form DnDToolbox
     */
    public DnDToolbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        characterFrame = new javax.swing.JFrame();
        searchCharacter = new javax.swing.JTextField();
        newCharacter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        previousCharacters = new javax.swing.JTextArea();
        itemFrame = new javax.swing.JFrame();
        searchItem = new javax.swing.JTextField();
        newItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemBoxPlaceHolder = new javax.swing.JTextArea();
        spellFrame = new javax.swing.JFrame();
        searchSpell = new javax.swing.JTextField();
        newSpell = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        spellBoxPlaceHolder = new javax.swing.JTextArea();
        monsterFrame = new javax.swing.JFrame();
        searchMonster = new javax.swing.JTextField();
        newMonster = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        monsterBoxPlaceHolder = new javax.swing.JTextArea();
        mapFrame = new javax.swing.JFrame();
        searchMap = new javax.swing.JTextField();
        saveMap = new javax.swing.JButton();
        newMap = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        mapBoxPlaceHolder = new javax.swing.JTextArea();
        lootFrame = new javax.swing.JFrame();
        searchLoot = new javax.swing.JTextField();
        newLoot = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lootBoxPlaceHolder = new javax.swing.JTextArea();
        encounterFrame = new javax.swing.JFrame();
        searchEncounter = new javax.swing.JTextField();
        newEncounter = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        encounterBoxPlaceHolder = new javax.swing.JTextArea();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        characterButton = new javax.swing.JButton();
        itemsButton = new javax.swing.JButton();
        spellsButton = new javax.swing.JButton();
        monstersButton = new javax.swing.JButton();
        mapsButton = new javax.swing.JButton();
        lootButton = new javax.swing.JButton();
        encounterButton = new javax.swing.JButton();


        searchCharacter.setText("Search...");
        searchCharacter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchCharacterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchCharacterFocusLost(evt);
            }
        });
        searchCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCharacterActionPerformed(evt);
            }
        });

        newCharacter.setText("New Character");
        newCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCharacterActionPerformed(evt);
            }
        });

        previousCharacters.setColumns(20);
        previousCharacters.setRows(5);
        previousCharacters.setText("Previous Characters and NPCs go here.");
        jScrollPane1.setViewportView(previousCharacters);

        javax.swing.GroupLayout characterFrameLayout = new javax.swing.GroupLayout(characterFrame.getContentPane());
        characterFrame.getContentPane().setLayout(characterFrameLayout);
        characterFrameLayout.setHorizontalGroup(
            characterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, characterFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(characterFrameLayout.createSequentialGroup()
                .addGroup(characterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(characterFrameLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(searchCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(characterFrameLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(newCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        characterFrameLayout.setVerticalGroup(
            characterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(characterFrameLayout.createSequentialGroup()
                .addComponent(searchCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(newCharacter)
                .addContainerGap())
        );


        searchItem.setText("Search...");
        searchItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchItemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchItemFocusLost(evt);
            }
        });
        searchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemActionPerformed(evt);
            }
        });

        newItem.setText("New Item");

        itemBoxPlaceHolder.setColumns(20);
        itemBoxPlaceHolder.setRows(5);
        itemBoxPlaceHolder.setText("Searched Items come up here.");
        jScrollPane2.setViewportView(itemBoxPlaceHolder);

        javax.swing.GroupLayout itemFrameLayout = new javax.swing.GroupLayout(itemFrame.getContentPane());
        itemFrame.getContentPane().setLayout(itemFrameLayout);
        itemFrameLayout.setHorizontalGroup(
            itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(itemFrameLayout.createSequentialGroup()
                .addGroup(itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemFrameLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(searchItem, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itemFrameLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(newItem, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        itemFrameLayout.setVerticalGroup(
            itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemFrameLayout.createSequentialGroup()
                .addComponent(searchItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(newItem)
                .addContainerGap())
        );


        searchSpell.setText("Search...");
        searchSpell.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchSpellFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchSpellFocusLost(evt);
            }
        });
        searchSpell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSpellActionPerformed(evt);
            }
        });

        newSpell.setText("New Spell");

        spellBoxPlaceHolder.setColumns(20);
        spellBoxPlaceHolder.setRows(5);
        spellBoxPlaceHolder.setText("Searched Spells come up here.");
        jScrollPane3.setViewportView(spellBoxPlaceHolder);

        javax.swing.GroupLayout spellFrameLayout = new javax.swing.GroupLayout(spellFrame.getContentPane());
        spellFrame.getContentPane().setLayout(spellFrameLayout);
        spellFrameLayout.setHorizontalGroup(
            spellFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spellFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(spellFrameLayout.createSequentialGroup()
                .addGroup(spellFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spellFrameLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(searchSpell, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(spellFrameLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(newSpell, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        spellFrameLayout.setVerticalGroup(
            spellFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spellFrameLayout.createSequentialGroup()
                .addComponent(searchSpell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(newSpell)
                .addContainerGap())
        );


        searchMonster.setText("Search...");
        searchMonster.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchMonsterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchMonsterFocusLost(evt);
            }
        });
        searchMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMonsterActionPerformed(evt);
            }
        });

        newMonster.setText("New Monster");

        monsterBoxPlaceHolder.setColumns(20);
        monsterBoxPlaceHolder.setRows(5);
        monsterBoxPlaceHolder.setText("Searched Monsters come up here.");
        jScrollPane4.setViewportView(monsterBoxPlaceHolder);

        javax.swing.GroupLayout monsterFrameLayout = new javax.swing.GroupLayout(monsterFrame.getContentPane());
        monsterFrame.getContentPane().setLayout(monsterFrameLayout);
        monsterFrameLayout.setHorizontalGroup(
            monsterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monsterFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(monsterFrameLayout.createSequentialGroup()
                .addGroup(monsterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monsterFrameLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(searchMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(monsterFrameLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(newMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        monsterFrameLayout.setVerticalGroup(
            monsterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monsterFrameLayout.createSequentialGroup()
                .addComponent(searchMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(newMonster)
                .addContainerGap())
        );


        searchMap.setText("Search...");
        searchMap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchMapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchMapFocusLost(evt);
            }
        });
        searchMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMapActionPerformed(evt);
            }
        });

        saveMap.setText("Save Map");
        saveMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMapActionPerformed(evt);
            }
        });

        newMap.setText("New Map");

        mapBoxPlaceHolder.setColumns(20);
        mapBoxPlaceHolder.setRows(5);
        mapBoxPlaceHolder.setText("Map displays here.");
        jScrollPane5.setViewportView(mapBoxPlaceHolder);

        javax.swing.GroupLayout mapFrameLayout = new javax.swing.GroupLayout(mapFrame.getContentPane());
        mapFrame.getContentPane().setLayout(mapFrameLayout);
        mapFrameLayout.setHorizontalGroup(
            mapFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapFrameLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(searchMap, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mapFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mapFrameLayout.createSequentialGroup()
                        .addComponent(newMap, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveMap, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );
        mapFrameLayout.setVerticalGroup(
            mapFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapFrameLayout.createSequentialGroup()
                .addComponent(searchMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(mapFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMap)
                    .addComponent(saveMap))
                .addContainerGap())
        );


        searchLoot.setText("Search...");
        searchLoot.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchLootFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchLootFocusLost(evt);
            }
        });
        searchLoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLootActionPerformed(evt);
            }
        });

        newLoot.setText("New Loot Item");

        lootBoxPlaceHolder.setColumns(20);
        lootBoxPlaceHolder.setRows(5);
        lootBoxPlaceHolder.setText("Searched Items come up here.");
        jScrollPane6.setViewportView(lootBoxPlaceHolder);

        javax.swing.GroupLayout lootFrameLayout = new javax.swing.GroupLayout(lootFrame.getContentPane());
        lootFrame.getContentPane().setLayout(lootFrameLayout);
        lootFrameLayout.setHorizontalGroup(
            lootFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lootFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(lootFrameLayout.createSequentialGroup()
                .addGroup(lootFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lootFrameLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(searchLoot, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lootFrameLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(newLoot, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        lootFrameLayout.setVerticalGroup(
            lootFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lootFrameLayout.createSequentialGroup()
                .addComponent(searchLoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(newLoot)
                .addContainerGap())
        );


        searchEncounter.setText("Search...");
        searchEncounter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchEncounterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchEncounterFocusLost(evt);
            }
        });
        searchEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEncounterActionPerformed(evt);
            }
        });

        newEncounter.setText("New Encounter");

        encounterBoxPlaceHolder.setColumns(20);
        encounterBoxPlaceHolder.setRows(5);
        encounterBoxPlaceHolder.setText("Searched Encounters come up here.");
        jScrollPane7.setViewportView(encounterBoxPlaceHolder);

        javax.swing.GroupLayout encounterFrameLayout = new javax.swing.GroupLayout(encounterFrame.getContentPane());
        encounterFrame.getContentPane().setLayout(encounterFrameLayout);
        encounterFrameLayout.setHorizontalGroup(
            encounterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encounterFrameLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(searchEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encounterFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(encounterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(encounterFrameLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(newEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );
        encounterFrameLayout.setVerticalGroup(
            encounterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encounterFrameLayout.createSequentialGroup()
                .addComponent(searchEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(newEncounter)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Welcome to the D&D Toolbox!");

        characterButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        characterButton.setText("Characters");
        characterButton.setPreferredSize(new java.awt.Dimension(70, 15));
        characterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                characterButtonMouseClicked(evt);
            }
        });
        characterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterButtonActionPerformed(evt);
            }
        });

        itemsButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemsButton.setText("Items");
        itemsButton.setPreferredSize(new java.awt.Dimension(70, 15));
        itemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsButtonMouseClicked(evt);
            }
        });
        itemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsButtonActionPerformed(evt);
            }
        });

        spellsButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spellsButton.setText("Spells");
        spellsButton.setPreferredSize(new java.awt.Dimension(70, 15));
        spellsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spellsButtonMouseClicked(evt);
            }
        });
        spellsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spellsButtonActionPerformed(evt);
            }
        });

        monstersButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monstersButton.setText("Monsters");
        monstersButton.setPreferredSize(new java.awt.Dimension(0, 0));
        monstersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monstersButtonMouseClicked(evt);
            }
        });

        mapsButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mapsButton.setText("Maps");
        mapsButton.setPreferredSize(new java.awt.Dimension(70, 15));
        mapsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapsButtonMouseClicked(evt);
            }
        });

        lootButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lootButton.setText("Loot");
        lootButton.setPreferredSize(new java.awt.Dimension(70, 15));
        lootButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lootButtonMouseClicked(evt);
            }
        });

        encounterButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        encounterButton.setText("Encounters");
        encounterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encounterButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(characterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spellsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monstersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mapsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lootButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(encounterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(characterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spellsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monstersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encounterButton)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void characterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_characterButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_characterButtonMouseClicked

    private void itemsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemsButtonMouseClicked

    private void spellsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spellsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_spellsButtonMouseClicked

    private void monstersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monstersButtonMouseClicked
        monsterFrame.setSize(875,538);
        monsterFrame.setLocationRelativeTo(null);
        monsterFrame.setVisible(true);
        characterFrame.setVisible(false);
        itemFrame.setVisible(false);
        spellFrame.setVisible(false);
        mapFrame.setVisible(false);
        lootFrame.setVisible(false);
        encounterFrame.setVisible(false);
    }//GEN-LAST:event_monstersButtonMouseClicked

    private void mapsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapsButtonMouseClicked
        mapFrame.setSize(875,538);
        mapFrame.setLocationRelativeTo(null);
        mapFrame.setVisible(true);
        characterFrame.setVisible(false);
        itemFrame.setVisible(false);
        monsterFrame.setVisible(false);
        spellFrame.setVisible(false);
        lootFrame.setVisible(false);
        encounterFrame.setVisible(false);
    }//GEN-LAST:event_mapsButtonMouseClicked

    private void lootButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lootButtonMouseClicked
        lootFrame.setSize(875,538);
        lootFrame.setLocationRelativeTo(null);
        lootFrame.setVisible(true);
        characterFrame.setVisible(false);
        itemFrame.setVisible(false);
        monsterFrame.setVisible(false);
        mapFrame.setVisible(false);
        spellFrame.setVisible(false);
        encounterFrame.setVisible(false);
    }//GEN-LAST:event_lootButtonMouseClicked

    private void encounterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encounterButtonMouseClicked
        encounterFrame.setSize(875,538);
        encounterFrame.setLocationRelativeTo(null);
        encounterFrame.setVisible(true);
        characterFrame.setVisible(false);
        itemFrame.setVisible(false);
        monsterFrame.setVisible(false);
        mapFrame.setVisible(false);
        lootFrame.setVisible(false);
        spellFrame.setVisible(false);
    }//GEN-LAST:event_encounterButtonMouseClicked

    private void itemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsButtonActionPerformed
        itemFrame.setSize(875,538);
        itemFrame.setLocationRelativeTo(null);
        itemFrame.setVisible(true);
        characterFrame.setVisible(false);
        spellFrame.setVisible(false);
        monsterFrame.setVisible(false);
        mapFrame.setVisible(false);
        lootFrame.setVisible(false);
        encounterFrame.setVisible(false);
        itemFrame.setVisible(true);

        //REMEMBER TO REMOVE REQUEST AUTO FOCUS FALSE TO FIX NO CLICK ON SEARCH BAR
        
    }//GEN-LAST:event_itemsButtonActionPerformed

    private void spellsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spellsButtonActionPerformed
        spellFrame.setSize(875,538);
        spellFrame.setLocationRelativeTo(null);
        spellFrame.setVisible(true);
        characterFrame.setVisible(false);
        itemFrame.setVisible(false);
        monsterFrame.setVisible(false);
        mapFrame.setVisible(false);
        lootFrame.setVisible(false);
        encounterFrame.setVisible(false);
    }//GEN-LAST:event_spellsButtonActionPerformed

    private void characterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterButtonActionPerformed
        characterFrame.setSize(875,538);
        characterFrame.setLocationRelativeTo(null);
        itemFrame.setVisible(false);
        spellFrame.setVisible(false);
        monsterFrame.setVisible(false);
        mapFrame.setVisible(false);
        lootFrame.setVisible(false);
        encounterFrame.setVisible(false);
        characterFrame.setVisible(true);

    }//GEN-LAST:event_characterButtonActionPerformed

    private void searchCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCharacterActionPerformed
        String input = searchCharacter.getText();
        System.out.println(input);
    }//GEN-LAST:event_searchCharacterActionPerformed

    private void searchCharacterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchCharacterFocusGained
        searchCharacter.setText("");
    }//GEN-LAST:event_searchCharacterFocusGained

    private void searchCharacterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchCharacterFocusLost
        searchCharacter.setEditable(true);
        searchCharacter.setText("Search...");
    }//GEN-LAST:event_searchCharacterFocusLost

    private void searchItemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchItemFocusGained
        searchItem.setText("");
    }//GEN-LAST:event_searchItemFocusGained

    private void searchItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchItemFocusLost
        searchItem.setEditable(true);
        searchItem.setText("Search...");
    }//GEN-LAST:event_searchItemFocusLost

    private void searchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchItemActionPerformed

    private void newCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCharacterActionPerformed
        jDialog1.setSize(991,802);
        jDialog1.setVisible(true);
        jDialog1.setLocationRelativeTo(null);

    }//GEN-LAST:event_newCharacterActionPerformed

    private void searchSpellFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchSpellFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSpellFocusGained

    private void searchSpellFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchSpellFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSpellFocusLost

    private void searchSpellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSpellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSpellActionPerformed

    private void searchMonsterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchMonsterFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonsterFocusGained

    private void searchMonsterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchMonsterFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonsterFocusLost

    private void searchMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMonsterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMonsterActionPerformed

    private void searchMapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchMapFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMapFocusGained

    private void searchMapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchMapFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMapFocusLost

    private void searchMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMapActionPerformed

    private void searchLootFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchLootFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchLootFocusGained

    private void searchLootFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchLootFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchLootFocusLost

    private void searchLootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchLootActionPerformed

    private void searchEncounterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchEncounterFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchEncounterFocusGained

    private void searchEncounterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchEncounterFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchEncounterFocusLost

    private void searchEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEncounterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchEncounterActionPerformed

    private void saveMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DnDToolbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DnDToolbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DnDToolbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DnDToolbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DnDToolbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton characterButton;
    private javax.swing.JFrame characterFrame;
    private javax.swing.JTextArea encounterBoxPlaceHolder;
    private javax.swing.JButton encounterButton;
    private javax.swing.JFrame encounterFrame;
    private javax.swing.JTextArea itemBoxPlaceHolder;
    private javax.swing.JFrame itemFrame;
    private javax.swing.JButton itemsButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea lootBoxPlaceHolder;
    private javax.swing.JButton lootButton;
    private javax.swing.JFrame lootFrame;
    private javax.swing.JTextArea mapBoxPlaceHolder;
    private javax.swing.JFrame mapFrame;
    private javax.swing.JButton mapsButton;
    private javax.swing.JTextArea monsterBoxPlaceHolder;
    private javax.swing.JFrame monsterFrame;
    private javax.swing.JButton monstersButton;
    private javax.swing.JButton newCharacter;
    private javax.swing.JButton newEncounter;
    private javax.swing.JButton newItem;
    private javax.swing.JButton newLoot;
    private javax.swing.JButton newMap;
    private javax.swing.JButton newMonster;
    private javax.swing.JButton newSpell;
    private javax.swing.JTextArea previousCharacters;
    private javax.swing.JButton saveMap;
    private javax.swing.JTextField searchCharacter;
    private javax.swing.JTextField searchEncounter;
    private javax.swing.JTextField searchItem;
    private javax.swing.JTextField searchLoot;
    private javax.swing.JTextField searchMap;
    private javax.swing.JTextField searchMonster;
    private javax.swing.JTextField searchSpell;
    private javax.swing.JTextArea spellBoxPlaceHolder;
    private javax.swing.JFrame spellFrame;
    private javax.swing.JButton spellsButton;
    // End of variables declaration//GEN-END:variables
}
